version: '3.8'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    ports:
      - "8008:8008"
    depends_on:
      - synapse_db
    volumes:
      - ./data:/data
    environment:
      - SYNAPSE_SERVER_NAME=matrix.rootpath.studio
      - SYNAPSE_REPORT_STATS=yes
    networks:
      - synapse_network
      - nginx_network

  synapse_db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - ./synapse_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD=mR8NPdDpO6EysUm
      - LC_COLLATE=C
      - LC_CTYPE=C
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    networks:
      - synapse_network

networks:
  nginx_network:
  synapse_network:

volumes:
  data:
  synapse_db_data:
