version: '3.8'

services:
  nextcloud_db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./nextcloud_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: your_password
    networks:
      - nextcloud_network

  nextcloud_app:
    image: nextcloud:29
    restart: always
    ports:
      - 8181:80
    links:
      - nextcloud_db
    volumes:
      - ./nextcloud_data:/var/www/html
    environment:
      MYSQL_HOST: nextcloud_db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: your_password
      OVERWRITEPROTOCOL: https
    networks:
      - nextcloud_network
      - nginx_network

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    networks:
      - nextcloud_network

networks:
  nginx_network:
  nextcloud_network:

volumes:
  nextcloud_db_data:
  nextcloud_data:
